### ISSUE TITLE
Impressive paper! Wondering the code release!

### ISSUE THREAD

**Issue by lanchen2019** [mworchel/differentiable-rendering-parametric#1]
Hi,
I am super curious about this differentiable rendering work of parametric geometry! This work is pretty interesting and impressive. Could you please release the code and share the details?
Thank you so much!
Lan.

**Comment by mworchel** [comment]
Hi,

thanks! I expect the code to be released next week. I'll leave this issue open until the release.

**Comment by lanchen2019** [comment]
Thank you!

**Comment by lanchen2019** [comment]
Hi,
Still waiting~
Thanks

**Comment by mworchel** [comment]
A first version is now released.
